Spring:
  #Application Properties
  application:
    name: movie-ticket-booking-system-api

  #Datasource Properties
  datasource:
    url: "${MYSQL_URL:jdbc:mysql://localhost:3306/movie-ticket-booking-system?createDatabaseIfNotExist=true}"
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PWD:root}"

  #JPA Details
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Internal Configuration
app:
  token:
    secret: "${TOKEN_SECRET:USgd9/hnmR0Ko3MPE0HplPywZc+PuyP8szM4NFCaek0=}"# Only for testing and development mode
